# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloCRC
ARDUINO_LIBS := AceCRC
include ../../../UnixHostDuino/UnixHostDuino.mk
