# See https://github.com/bxparks/UnixHostDuino for documentation about using
# UnixHostDuino to compile and run AUnit tests natively on Linux or MacOS.

APP_NAME := CpuBenchmark
ARDUINO_LIBS := AceCommon AceCRC
MORE_CLEAN := more_clean
include ../../../UnixHostDuino/UnixHostDuino.mk
