# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Crc8Test
ARDUINO_LIBS := AUnit AceCRC
include ../../../UnixHostDuino/UnixHostDuino.mk
