# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := Crc16CcittTest
ARDUINO_LIBS := AUnit AceCRC
include ../../../EpoxyDuino/EpoxyDuino.mk
